/* Auto-generated by genmsg_cpp for file /home/robotlab/fuerte_workspace/drone_movement/msg/pos.msg */
#ifndef DRONE_MOVEMENT_MESSAGE_POS_H
#define DRONE_MOVEMENT_MESSAGE_POS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace drone_movement
{
template <class ContainerAllocator>
struct pos_ {
  typedef pos_<ContainerAllocator> Type;

  pos_()
  : fXPos(0.0)
  , fYPos(0.0)
  , fYawAngle(0.0)
  {
  }

  pos_(const ContainerAllocator& _alloc)
  : fXPos(0.0)
  , fYPos(0.0)
  , fYawAngle(0.0)
  {
  }

  typedef float _fXPos_type;
  float fXPos;

  typedef float _fYPos_type;
  float fYPos;

  typedef float _fYawAngle_type;
  float fYawAngle;


  typedef boost::shared_ptr< ::drone_movement::pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_movement::pos_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct pos
typedef  ::drone_movement::pos_<std::allocator<void> > pos;

typedef boost::shared_ptr< ::drone_movement::pos> posPtr;
typedef boost::shared_ptr< ::drone_movement::pos const> posConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::drone_movement::pos_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::drone_movement::pos_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace drone_movement

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::drone_movement::pos_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::drone_movement::pos_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::drone_movement::pos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "07182b1076047fa59cc732e44299f292";
  }

  static const char* value(const  ::drone_movement::pos_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x07182b1076047fa5ULL;
  static const uint64_t static_value2 = 0x9cc732e44299f292ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_movement::pos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "drone_movement/pos";
  }

  static const char* value(const  ::drone_movement::pos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::drone_movement::pos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 fXPos\n\
float32 fYPos\n\
float32 fYawAngle\n\
\n\
";
  }

  static const char* value(const  ::drone_movement::pos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::drone_movement::pos_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::drone_movement::pos_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.fXPos);
    stream.next(m.fYPos);
    stream.next(m.fYawAngle);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct pos_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_movement::pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::drone_movement::pos_<ContainerAllocator> & v) 
  {
    s << indent << "fXPos: ";
    Printer<float>::stream(s, indent + "  ", v.fXPos);
    s << indent << "fYPos: ";
    Printer<float>::stream(s, indent + "  ", v.fYPos);
    s << indent << "fYawAngle: ";
    Printer<float>::stream(s, indent + "  ", v.fYawAngle);
  }
};


} // namespace message_operations
} // namespace ros

#endif // DRONE_MOVEMENT_MESSAGE_POS_H

